name: 'Config Env'
description: 'Config Env'
inputs:
  branch:
    description: 'Current branch name'
    required: true
  branch-prod:
    description: 'Production branch name'
    required: true
outputs:
  deploy_stage:
    description: 'Deploy stage'
  image_tag:
    description: 'Image tag'

runs:
  using: 'node16'
  main: 'dist/index.js'
