name: Test this action

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Test this action (prod)
        id: prod
        uses: ./
        with:
          branch: ${{ github.ref_name }}
          branch-prod: master

      - name: Test this action (dev)
        id: dev
        uses: ./
        with:
          branch: dev
          branch-prod: master

      - name: Check result
        run: |
          echo 'Deploy Stage(prod) : ${{ steps.prod.outputs.deploy_stage }}'
          echo 'Image Tag(prod) : ${{ steps.prod.outputs.image_tag }}'
          echo ''
          echo 'Deploy Stage(dev) : ${{ steps.dev.outputs.deploy_stage }}'
          echo 'Image Tag(dev) : ${{ steps.dev.outputs.image_tag }}'
